// // Generated by post-build.js
// import { ctlCdAdminSettings } from './cd-admin-settings.controller';

// export const cdAdminModule = {
//   ctx: "sys",
//   moduleId: "cd-admin",
//   moduleName: "cd-admin",
//   moduleGuid: "aaaa-bbbb-cccc-dddd",
//   // controller: ctlCdAdminSettings,
//   // template: ctlCdAdminSettings.__template(),
//   controllers: [
//     { name: "settings", instance: ctlCdAdminSettings, template: ctlCdAdminSettings.__template(), default: false, },
//   ],
//   menu: [ // Menu structure is generated separately or hardcoded
//     {
//       label: 'cd-admin',
//       route: 'sys/cd-admin',
//       children: [
//         { label: 'settings', itemType: 'route', route: 'sys/cd-admin/settings', template: ctlCdAdminSettings.__template() },
//       ]
//     }
//   ], 
// };

// export const module = cdAdminModule;

// src/CdShell/sys/cd-admin/view/index.js
// Generated by post-build.js — modified for runtime lifecycle harmony

import { ctlCdAdminSettings } from "./cd-admin-settings.controller.js";

/**
 * 🧩 Corpdesk Admin Module View Index
 * -----------------------------------
 * This module definition now fully supports the Corpdesk UUD lifecycle.
 *
 * ✨ Key Fix:
 * - Templates are no longer pre-evaluated at import time.
 * - Each `template` is a function bound at runtime (via MenuService.loadResource()).
 * - Prevents getters from executing before __init() / __setup().
 */

export const cdAdminModule = {
  ctx: "sys",
  moduleId: "cd-admin",
  moduleName: "cd-admin",
  moduleGuid: "aaaa-bbbb-cccc-dddd",

  /**
   * Controllers
   * Each controller entry contains the instance and a lazy-loaded template.
   */
  controllers: [
    {
      name: "settings",
      instance: ctlCdAdminSettings,

      /**
       * 🕓 Template is now a function — executed at runtime using the controller context.
       * This ensures getters (like uiSystemOptionsHtml, themeOptionsHtml, etc.) run correctly.
       */
      template: function () {
        if (typeof this.__template === "function") {
          return this.__template();
        } else {
          console.warn("[cdAdminModule] Missing __template() on controller:", this);
          return "<div>Template not available.</div>";
        }
      },
      default: false,
    },
  ],

  /**
   * Menu definition for the module.
   * Each route item now references a runtime template function as well.
   */
  menu: [
    {
      label: "cd-admin",
      route: "sys/cd-admin",
      children: [
        {
          label: "settings",
          itemType: "route",
          route: "sys/cd-admin/settings",

          // 🟢 Lazy template resolution — called at runtime by MenuService
          template: function () {
            if (typeof this.__template === "function") {
              return this.__template();
            } else {
              console.warn("[Menu][cd-admin/settings] Missing __template()");
              return "<div>Template missing for cd-admin/settings.</div>";
            }
          },
        },
      ],
    },
  ],
};

/**
 * 🔄 Exported alias for module loaders
 */
export const module = cdAdminModule;


