// // src/CdShell/adm/admin/view/index.ts

// // 1. Import the primary controller and assume the runtime file exports 'ctlAdminSetting'
// import { ctlAdminSetting } from "./cd-admin-settings.controller.js"; 

// // 2. Define the Admin Module structure
// export const cdadminModule = {
//   ctx: "adm", 
//   moduleId: "admin",
//   moduleName: "Admin Settings",
//   moduleGuid: "adm-settings-guid", 
  
//   // The default module view uses the settings controller template
//   controller: ctlAdminSetting, 
//   template: ctlAdminSetting.__template(), 
  
//   // 3. Define the internal menu structure as requested
//   menu: [ 
//     {
//       label: 'cd-admin',
//       // Note: Assuming the route should be adm/admin, not sys/cd-admin based on folder structure
//       route: 'adm/admin', 
//       children: [
//         { 
//           label: 'settings', 
//           route: 'adm/admin/settings', // Sub-route
//           // Use the correct export name for the template
//           template: ctlAdminSetting.__template() 
//         },
//       ]
//     }
//   ], 
// };

// /**
//  * The entry export for the ModuleService.
//  */
// export const module = cdadminModule;

/////////////////////////////////////////////////////////////////////////////////

// // Optional: Re-export the controller for routing/template systems
// export const ctlCdAdminSettings = ctlAdminSetting; // 👈 Providing the full name for internal clarity

// import { CdAdminSettings } from './cd-admin-settings.controller.js';

// /**
//  * cd-admin/views/index.js
//  * Registers all view controllers for cd-admin module.
//  */
// export const CdAdminViews = {
//   settings: CdAdminSettings,
// };

// /**
//  * Optional helper for future dynamic loading
//  */
// export function getCdAdminView(name) {
//   return CdAdminViews[name] || null;
// }

////////////////////////////////////////////////////////////////////

// Generated by post-build.js
import { ctlCdAdminSettings } from './cd-admin-settings.controller';

export const cdAdminModule = {
  ctx: "sys",
  moduleId: "cd-admin",
  moduleName: "cd-admin",
  moduleGuid: "aaaa-bbbb-cccc-dddd",
  controller: ctlCdAdminSettings,
  template: ctlCdAdminSettings.__template(),
  menu: [ // Menu structure is generated separately or hardcoded
    {
      label: 'admin',
      route: 'sys/cd-admin',
      children: [
        { label: 'settings', route: 'sys/cd-admin/settings', template: ctlCdAdminSettings.__template() },
      ]
    }
  ], 
};

export const module = cdAdminModule;

