// Generated by post-build.js
import { ctlSession } from "./session.controller.js";
import { ctlSignIn } from "./sign-in.controller.js";
import { ctlUser } from "./user.controller.js";

export const cduserModule = {
  ctx: "sys",
  moduleId: "cd-user",
  moduleName: "Auto-Generated Module",
  moduleGuid: "auto-guid",
  controller: ctlSignIn,
  template: ctlSignIn.__template(),
  menu: [], // Menu structure must be generated separately or hardcoded
};

export const module = cduserModule;
