// Generated by post-build.js
// import { ctlSession } from "./session.controller.js";
import { ctlSignIn } from "./sign-in.controller.js";
import { ctlSignUp } from "./sign-up.controller.js";
// import { ctlUser } from "./user.controller.js";

export const cdUserModule = {
  ctx: "sys",
  isDefault: true,
  moduleId: "cd-user",
  moduleName: "Auto-Generated Module",
  moduleGuid: "auto-guid",
  // controller: ctlSignIn,
  // template: ctlSignIn.__template(),
  controllers: [
    { name: "sign-in", instance: ctlSignIn, template: ctlSignIn.__template(), default: true, },
    { name: "sign-up", instance: ctlSignUp, template: ctlSignUp.__template(), default: false, },
    // { name: "session", instance: ctlSession, template: ctlSession.__template(), default: false, },
  ],
  menu: [ // Menu structure is generated separately or hardcoded
    {
      label: 'cd-user',
      route: 'sys/cd-user',
      children: [
        { label: 'sign-in', itemType: 'route',  route: 'sys/cd-user/sign-in', template: ctlSignIn.__template() },
        { label: 'sign-up', itemType: 'route', route: 'sys/cd-user/sign-up', template: ctlSignUp.__template() }
      ]
    }
  ], 
};

export const module = cdUserModule;
