// Generated by post-build.js
// import { ctlSession } from "./session.controller.js";
import { ctlSignIn } from "./sign-in.controller.js";
import { ctlSignUp } from "./sign-up.controller.js";
// import { ctlUser } from "./user.controller.js";

export const cduserModule = {
  ctx: "sys",
  moduleId: "cd-user",
  moduleName: "Auto-Generated Module",
  moduleGuid: "auto-guid",
  controller: ctlSignIn,
  template: ctlSignIn.__template(),
  menu: [ // Menu structure is generated separately or hardcoded
    {
      label: 'User',
      route: 'sys/cd-user',
      children: [
        { label: 'Sign In', route: 'sys/cd-user/sign-in', template: ctlSignIn.__template() },
        { label: 'Sign Up', route: 'sys/cd-user/sign-up', template: ctlSignUp.__template() }
      ]
    }
  ], 
};

export const module = cduserModule;
