// Generated by post-build.js
import { ctlCdLogger } from "./cd-logger.controller.js";

export const cdcommModule = {
  ctx: "sys",
  moduleId: "cd-comm",
  moduleName: "Auto-Generated Module",
  moduleGuid: "auto-guid",
  controller: ctlCdLogger,
  template: ctlCdLogger.__template(),
  menu: [], // Menu structure must be generated separately or hardcoded
};

export const module = cdcommModule;
